apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fresh-deployment.yaml
  - httproute.yaml
  - prefixes.yaml
  - volumes.yaml
  - freshrss-config.yaml
  - database.yaml
configMapGenerator:
  - files:
      - 20-memcached.ini
    name: php-ini-config
