[language-server.yaml-language-server.config.yaml.schemas]
"Kubernetes" = [
  "database.yaml",
  "fresh-deployment.yaml",
  "freshrss-config.yaml",
  "httproute.yaml",
  "prefixes.yaml",
  "volumes.yaml",
]
